[INJIWEB-1002]: injiweb Online Sharing properties & fallback wellknowns
mosip/inji-config pull request #379
Opened 2024-10-17 07:01 UTC by vijay151096

2024-10-17 08:02 UTC, swatigoel requested changes
Let's replace `mosip.esignet.host` by `mosip.esignet.mosipid.host` in mimoto-default.properties and mimoto-issuer-config.json and fallback wellknown

2024-10-17 08:30 UTC, vijay151096 commented
> Let's replace `mosip.esignet.host` by `mosip.esignet.mosipid.host` in mimoto-default.properties and mimoto-issuer-config.json and fallback wellknown

Updated the host to use case specific

2024-10-18 05:05 UTC, Prafulrakhade approved these changes

2024-10-18 05:10 UTC, swatigoel approved these changes

2024-10-18 05:10 UTC, merged